<b>1. Write a Python program to select an item randomly from a list.</b>

In [7]:
import random
arr=[1,2,3,4,5]
print("Printing random element from array: ", arr[random.randint(0,5)])

Printing random element from array:  3


<b>2. Write a Python program to count the elements in a list until an element is a tuple</b>

In [38]:
arr=(1,2,3,(1,))
count=0
for i in arr:
    if(type(i)==type((1,))):
        break;
    else:
        count+=1
print(count)

3


<b>3. Create a dictionary of 5 countries with their currency details and display them</b>

In [49]:
dict={
    "india":"Rupee",
    "USA":"Dollar",
    "U.K":"Pound sterling",
    "Germany":"Euro",
    "Japan":"Yen"
}
print(dict)

{'india': 'Rupee', 'USA': 'Dollar', 'U.K': 'Pound sterling', 'Germany': 'Euro', 'Japan': 'Yen'}


<b>4. Write a Python program to reverse a tuple.</b>

In [59]:
arr=(1,2,3,4,5)
print(arr[::-1])

(5, 4, 3, 2, 1)


<b>5. Create a Numpy array filled with all ones</b>

In [69]:
import numpy as np
arr=np.array([])
type(arr)

numpy.ndarray

<b>6. Check whether a Numpy array contains a specified row</b>

In [75]:
import numpy as np
arr=np.array([[1],[1,2],[1,2,3],[1,2,3,4]])

for i in arr:
    if(i==[1,2]):
        print(True)

True


<ipython-input-75-1b28e98699be>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1],[1,2],[1,2,3],[1,2,3,4]])


<b>7. Compute mathematical operations on Array, Add & Multiply two matrices</b>

In [80]:
import numpy as np
arr=np.array([[1,0],[0,1]])
arr1=np.array([[1,0],[0,1]])
print(arr+arr1,"\n")
print(arr*arr1)

[[2 0]
 [0 2]] 

[[1 0]
 [0 1]]


<b>8. Find the most frequent value in a NumPy array</b>

In [5]:
import numpy as np
arr=np.array([1,1,1,1,1,2,3,4,5])
print(np.bincount(arr).argmax())

1


<b>9. Flatten a 2d numpy array into ld array</b>

In [8]:
import numpy as np
arr=np.array([[1],[1,2],[1,2,3],[1,2,3,4]])
print(arr.flatten())

[list([1]) list([1, 2]) list([1, 2, 3]) list([1, 2, 3, 4])]


<ipython-input-8-34f15c819fa0>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1],[1,2],[1,2,3],[1,2,3,4]])


<b>10. Calculate the sum of all columns in a 2D NumPy array</b>

In [20]:
import numpy as np

def colsum(arr, n, m):
    for i in range(n):
        su = 0;
        for j in range(m):
            su += arr[j][i]
        print(su, end = " ")  
        
arr=np.array([[1],[1,2],[1,2,3],[1,2,3,4]])
colsum(arr,len(arr[0]), len(arr))

4 

<ipython-input-20-4a89e34a8764>:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1],[1,2],[1,2,3],[1,2,3,4]])


<b>11. Calculate the average, variance and standard deviation in Python using NumPy</b>

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Average: ", np.average(arr))
print("Variance: ", np.var(arr))
print("Standard Deviation: ", np.std(arr))

Average:  5.5
Variance:  8.25
Standard Deviation:  2.8722813232690143


<b>12. Insert a space between characters of all the elements of a given NumPy array?</b>

In [45]:
import numpy as np 
x = np.array(["ayush", "anish", "bhavesh"])
r = np.char.join(' ', x)
print("Printing the array after inserting space between the elements") 
print(r) 

Printing the array after inserting space between the elements
['a y u s h' 'a n i s h' 'b h a v e s h']


<b>13. Sort the values in a matrix</b>

In [46]:
import numpy as np 
arr = np.matrix('[4, 1; 12, 3]') 
arr.sort() 
print(arr) 

[[ 1  4]
 [ 3 12]]
